'use client';

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import type { Prospect } from '../lib/types';

const emptyForm={name:'',category:'',city:'León, Gto.',website:'',phone:'',whatsapp:''}; type ProspectForm=typeof emptyForm;
const MIN_SCORE_FOR_AI=60;
const discoveryCategories=[['dentistas','Dentistas'],['psicologos','Psicólogos'],['abogados','Abogados'],['arquitectos','Arquitectos'],['talleres','Talleres'],['inmobiliarias','Inmobiliarias'],['clinicas','Clínicas'],['restaurantes','Restaurantes'],['belleza','Belleza']] as const;
export default function Home(){
 const [prospects,setProspects]=useState<Prospect[]>([]),[selected,setSelected]=useState<Prospect|null>(null); const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false); const [error,setError]=useState(''),[notice,setNotice]=useState(''); const [showForm,setShowForm]=useState(false),[showDiscover,setShowDiscover]=useState(false),[editing,setEditing]=useState(false); const [form,setForm]=useState<ProspectForm>(emptyForm),[editForm,setEditForm]=useState<ProspectForm>(emptyForm); const [discover,setDiscover]=useState({city:'León, Guanajuato',category:'dentistas',limit:20}); const fileRef=useRef<HTMLInputElement>(null);
 async function loadProspects(){setLoading(true);setError('');try{const r=await fetch('/api/prospects',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudieron cargar');setProspects(d);setSelected(c=>c?d.find((p:Prospect)=>p.id===c.id)||d[0]||null:d[0]||null)}catch(e){setError(e instanceof Error?e.message:'Error inesperado')}finally{setLoading(false)}}
 useEffect(()=>{void loadProspects()},[]); useEffect(()=>{if(selected)setEditForm({name:selected.name,category:selected.category,city:selected.city,website:selected.website||'',phone:selected.phone||'',whatsapp:selected.whatsapp||''})},[selected]);
 const stats=useMemo(()=>({total:prospects.length,qualified:prospects.filter(p=>p.opportunityScore>=70).length,demos:prospects.filter(p=>['DEMO_CREATED','CONTACTED','RESPONDED','INTERESTED','WON'].includes(p.status)).length,contacted:prospects.filter(p=>['CONTACTED','RESPONDED','FOLLOWUP_1','FOLLOWUP_2','INTERESTED','WON'].includes(p.status)).length,won:prospects.filter(p=>p.status==='WON').length,pending:prospects.filter(p=>!p.mainProblem&&['NEW','QUALIFIED'].includes(p.status)&&p.opportunityScore>=MIN_SCORE_FOR_AI).length,lowScore:prospects.filter(p=>!p.mainProblem&&['NEW','QUALIFIED'].includes(p.status)&&p.opportunityScore<MIN_SCORE_FOR_AI).length}),[prospects]);
 function applyProspect(n:Prospect){setProspects(a=>a.map(x=>x.id===n.id?n:x));setSelected(n)}
 async function patchStatus(p:Prospect,status:Prospect['status']){setBusy(true);setError('');try{const r=await fetch(`/api/prospects/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})}),n=await r.json();if(!r.ok)throw new Error(n.error);applyProspect(n)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 async function analyze(p:Prospect){setBusy(true);setError('');try{const r=await fetch(`/api/prospects/${p.id}/analyze`,{method:'POST'}),n=await r.json();if(!r.ok)throw new Error(n.error);applyProspect(n);setNotice(`Análisis completado. Score: ${n.opportunityScore}/100.`)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 async function analyzeBatch(){setBusy(true);setError('');setNotice('Analizando hasta 5 prospectos elegibles...');try{const r=await fetch('/api/prospects/analyze-batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:5,minScoreForAI:MIN_SCORE_FOR_AI,autoDemoMinScore:70})}),d=await r.json();if(!r.ok)throw new Error(d.error);await loadProspects();const failures=(d.results||[]).filter((x:{ok:boolean})=>!x.ok);setNotice(`${d.analyzed} analizados · ${d.qualified} con score ≥70 · ${d.demos} demos · ${d.skippedLowScore||0} descartados de IA por score <${MIN_SCORE_FOR_AI}${d.failed?` · ${d.failed} con error`:''}.`);if(failures.length)setError(failures.map((x:{name:string;error?:string})=>`${x.name}: ${x.error||'Error desconocido'}`).join('\n\n'))}catch(e){setError(e instanceof Error?e.message:'Error inesperado');setNotice('')}finally{setBusy(false)}}
 async function createProspect(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/prospects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error);setProspects(a=>[d,...a]);setSelected(d);setShowForm(false)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 async function discoverBusinesses(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/prospects/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(discover)}),d=await r.json();if(!r.ok)throw new Error(d.error);await loadProspects();setNotice(d.count?`${d.count} negocios nuevos encontrados y guardados en PostgreSQL.`:d.message)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);try{const r=await fetch(`/api/prospects/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(editForm)}),d=await r.json();if(!r.ok)throw new Error(d.error);applyProspect(d);setEditing(false)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 async function removeSelected(){if(!selected||!confirm(`¿Eliminar ${selected.name}?`))return;setBusy(true);try{await fetch(`/api/prospects/${selected.id}`,{method:'DELETE'});await loadProspects()}finally{setBusy(false)}}
 async function importCsv(file:File){setBusy(true);try{const text=await file.text(),rows=parseCsv(text),headers=rows[0].map(normalizeHeader);const value=(row:string[],key:string)=>row[headers.indexOf(key)]?.trim()||'';const items=rows.slice(1).filter(r=>r.some(v=>v.trim())).map(row=>({name:value(row,'name'),category:value(row,'category'),city:value(row,'city'),website:value(row,'website'),phone:value(row,'phone'),whatsapp:value(row,'whatsapp')})).filter(x=>x.name&&x.category&&x.city);const r=await fetch('/api/prospects/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prospects:items})}),d=await r.json();if(!r.ok)throw new Error(d.error);await loadProspects();setNotice(`${d.count} prospectos importados.`)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}}
 return <main className="shell"><header className="topbar"><div className="brand"><h1>Prospección IA</h1><p>PostgreSQL propio + descubrimiento + scoring + demos personalizadas</p></div><div className="toolbar"><input ref={fileRef} hidden type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&void importCsv(e.target.files[0])}/><button className="btn secondary" disabled={busy} onClick={()=>setShowDiscover(v=>!v)}>{showDiscover?'Cerrar búsqueda':'Buscar negocios'}</button><button className="btn secondary" disabled={busy||!stats.pending} onClick={()=>void analyzeBatch()}>{busy?'Procesando...':`Analizar elegibles (${stats.pending})`}</button><button className="btn secondary" onClick={()=>fileRef.current?.click()}>Importar CSV</button><button className="btn" onClick={()=>setShowForm(v=>!v)}>+ Agregar prospecto</button></div></header>
 {error&&<div className="card" style={{marginBottom:18,borderColor:'#7f1d1d',whiteSpace:'pre-wrap'}}><strong>Detalle del error:</strong><br/>{error}</div>}{notice&&<div className="card" style={{marginBottom:18,borderColor:'#166534'}}>{notice}</div>}
 {showDiscover&&<section className="card" style={{marginBottom:24}}><h2>Buscar negocios reales</h2><form onSubmit={discoverBusinesses} className="form-grid"><Editable label="Ciudad" value={discover.city} onChange={v=>setDiscover({...discover,city:v})}/><div className="field"><label>Categoría</label><select value={discover.category} onChange={e=>setDiscover({...discover,category:e.target.value})}>{discoveryCategories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="field"><label>Máximo</label><input type="number" value={discover.limit} onChange={e=>setDiscover({...discover,limit:Number(e.target.value)})}/></div><button className="btn">Buscar y guardar</button></form></section>}
 {showForm&&<section className="card"><form onSubmit={createProspect} className="form-grid"><Editable label="Negocio" value={form.name} onChange={v=>setForm({...form,name:v})}/><Editable label="Categoría" value={form.category} onChange={v=>setForm({...form,category:v})}/><Editable label="Ciudad" value={form.city} onChange={v=>setForm({...form,city:v})}/><button className="btn">Guardar</button></form></section>}
 <section className="grid stats"><Stat label="Prospectos" value={stats.total}/><Stat label={`Elegibles IA ≥${MIN_SCORE_FOR_AI}`} value={stats.pending}/><Stat label="No gastar IA" value={stats.lowScore}/><Stat label="Calificados ≥70" value={stats.qualified}/><Stat label="Demos" value={stats.demos}/><Stat label="Contactados" value={stats.contacted}/><Stat label="Ventas" value={stats.won}/></section>
 <section className="split"><div className="card"><h2>Pipeline {loading?'· cargando...':''}</h2><table className="table"><thead><tr><th>Negocio</th><th>Sector</th><th>Score</th><th>Estado</th></tr></thead><tbody>{prospects.map(p=><tr key={p.id} onClick={()=>setSelected(p)} style={{cursor:'pointer'}}><td>{p.name}<div className="muted">{p.city}</div></td><td>{p.category}</td><td className="score">{p.opportunityScore}</td><td><span className="badge">{p.status}</span></td></tr>)}</tbody></table></div><aside className="card"><h2>Prospecto seleccionado</h2>{selected&&<>{editing?<form onSubmit={saveEdit}><Editable label="Negocio" value={editForm.name} onChange={v=>setEditForm({...editForm,name:v})}/><button className="btn">Guardar</button></form>:<><div className="form-grid"><Field label="Negocio" value={selected.name}/><Field label="Categoría" value={selected.category}/><Field label="Ciudad" value={selected.city}/><Field label="Score objetivo" value={String(selected.opportunityScore)}/><div className="field full"><label>Problema detectado</label><textarea readOnly value={selected.mainProblem||'Pendiente de análisis IA'}/></div><div className="field full"><label>Mensaje sugerido</label><textarea readOnly value={selected.personalizedMessage||'Pendiente'}/></div></div><div className="toolbar"><button className="btn" disabled={busy} onClick={()=>analyze(selected)}>Analizar con IA</button><button className="btn secondary" onClick={()=>patchStatus(selected,'DEMO_CREATED')}>Generar demo</button><a className="btn secondary" href={`/demo/${selected.id}`} target="_blank">Ver demo</a><button className="btn secondary" onClick={()=>setEditing(true)}>Editar</button><button className="btn secondary" onClick={removeSelected}>Eliminar</button></div></>}</>}</aside></section></main>}
function Stat({label,value}:{label:string;value:number}){return <div className="card stat"><span>{label}</span><strong>{value}</strong></div>}function Field({label,value}:{label:string;value:string}){return <div className="field"><label>{label}</label><input readOnly value={value}/></div>}function Editable({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className="field"><label>{label}</label><input value={value} onChange={e=>onChange(e.target.value)}/></div>}
function normalizeHeader(v:string){return v.trim().toLowerCase().replace(/[ _-]/g,'')}function parseCsv(text:string){return text.trim().split(/\r?\n/).map(line=>line.split(',').map(v=>v.replace(/^"|"$/g,'').trim()))}
